
(function(){
  var demoStore={get:function(k){try{var r=window.localStorage.getItem('loungeDemo.'+k);return r?JSON.parse(r):null}catch(e){return null}},set:function(k,v){try{window.localStorage.setItem('loungeDemo.'+k,JSON.stringify(v))}catch(e){}},reset:function(){try{Object.keys(window.localStorage).filter(function(k){return k.indexOf('loungeDemo.')===0}).forEach(function(k){window.localStorage.removeItem(k)})}catch(e){}}};
  window.demoStore=demoStore;
  document.getElementById('resetDemo').addEventListener('click',function(){demoStore.reset();location.reload();});
})();
(function(){
  var drawer=document.getElementById('drawer'),overlay=document.getElementById('overlay'),toast=document.getElementById('toast');
  var cards=Array.from(document.querySelectorAll('.station'));
  function parseClock(value){if(!/^\d\d:\d\d:\d\d$/.test(value))return 0;var parts=value.split(':').map(Number);return parts[0]*3600+parts[1]*60+parts[2]}
  function formatClock(seconds){seconds=Math.max(0,Math.floor(seconds));return String(Math.floor(seconds/3600)).padStart(2,'0')+':'+String(Math.floor(seconds%3600/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0')}
  var stationData=cards.map(function(card){var state=card.querySelector('.timer-row small').textContent,remainingMatch=state.match(/(\d+) min left/);return{name:card.dataset.name,type:card.dataset.type,player:card.dataset.player,game:card.dataset.game,time:card.dataset.time,status:card.querySelector('.status').textContent,state:state,price:card.querySelector('.player > b').textContent,elapsed:parseClock(card.dataset.time),remaining:remainingMatch?Number(remainingMatch[1])*60:0,paused:false,tvOn:card.dataset.time!=='Standby',paid:true,history:['Console connected · LAN command ready']}});
  (function(s){if(Array.isArray(s)&&s.length===stationData.length){s.forEach(function(saved,i){if(saved&&saved.name===stationData[i].name){Object.assign(stationData[i],saved)}});stationData.forEach(function(_,i){syncOverview(i)})}})(demoStore.get('stations'));
  var selectedIndex=0,drawerIndex=0;
  function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(function(){toast.classList.remove('show')},2200)}
  function closeDrawer(){drawer.classList.remove('open');overlay.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.querySelectorAll('.station').forEach(function(s){s.classList.remove('selected')})}
  function refreshDrawer(){var item=stationData[drawerIndex];if(!item)return;document.getElementById('drawerTitle').textContent=item.name;document.getElementById('drawerMeta').textContent=item.type+' · '+item.status+(item.paused?' · Paused':'');document.getElementById('drawerPlayer').textContent=item.player;document.getElementById('drawerGame').textContent=item.game;document.getElementById('drawerTime').textContent=item.time;document.getElementById('drawerConnection').textContent=item.time==='Standby'?'Standby':'Online'}
  function openStation(card){drawerIndex=cards.indexOf(card);document.querySelectorAll('.station').forEach(function(s){s.classList.remove('selected')});card.classList.add('selected');refreshDrawer();drawer.classList.add('open');overlay.classList.add('open');drawer.setAttribute('aria-hidden','false')}
  cards.forEach(function(card){card.addEventListener('click',function(){openStation(card)})});
  document.getElementById('drawerClose').addEventListener('click',closeDrawer);overlay.addEventListener('click',closeDrawer);

  function showView(name){if((name==='analytics'||name==='games')&&document.body.classList.contains('role-limited')){showToast(name==='games'?'Game control is owner-only':'Revenue analytics are owner-only');return}var views={overview:'overviewView',stations:'stationsView',reservations:'reservationsView',tournaments:'tournamentsView',competition:'competitionView',payments:'paymentsView',customers:'customersView',games:'gamesView',analytics:'analyticsView'},target=views[name]||views.overview;document.querySelectorAll('.view').forEach(function(view){view.classList.toggle('active',view.id===target)});document.querySelectorAll('[data-view-target]').forEach(function(btn){btn.classList.toggle('active',btn.dataset.viewTarget===name)});window.scrollTo(0,0)}
  document.querySelectorAll('[data-view-target]').forEach(function(btn){btn.addEventListener('click',function(){showView(btn.dataset.viewTarget)})});
  document.getElementById('backOverview').addEventListener('click',function(){showView('overview')});
  document.getElementById('allStations').addEventListener('click',function(){showView('stations')});
  document.querySelectorAll('.nav button:not([data-view-target]),.mobile-nav button:not([data-view-target])').forEach(function(btn){if(btn.id!=='mobileAdd')btn.addEventListener('click',function(){showToast(btn.textContent.trim()+' is shown as a navigation preview')})});

  function renderRail(){var rail=document.getElementById('stationRail');rail.innerHTML='';stationData.forEach(function(item,index){var btn=document.createElement('button');btn.className='rail-item'+(index===selectedIndex?' active':'');var code=item.type.indexOf('5')>-1?'PS5':'PS4';var dotClass=item.status==='Playing'?'playing':(item.status.indexOf('min')>-1?'warning':'');btn.innerHTML='<span class="rail-code">'+code+'</span><span><b>'+item.name+'</b><small>'+item.status+(item.paused?' · Paused':'')+' · '+item.player+'</small></span><i class="rail-dot '+dotClass+'"></i>';btn.addEventListener('click',function(){selectStation(index)});rail.appendChild(btn)})}
  function activeSession(item){return item.status==='Playing'||item.status.indexOf('min')>-1}
  function displayState(item){if(item.paused)return 'Paused by staff';if(item.remaining>0)return Math.max(1,Math.ceil(item.remaining/60))+' min left';return item.state}
  function selectStation(index){selectedIndex=index;var item=stationData[index],isStandby=item.time==='Standby',isActive=activeSession(item);renderRail();document.getElementById('consoleTitle').textContent=item.name;document.getElementById('consoleMeta').textContent=item.type+' · '+item.game;document.getElementById('consoleTimer').textContent=item.time;document.getElementById('consoleState').textContent=displayState(item);document.getElementById('consolePower').textContent=isStandby?'Standby':'Online';document.getElementById('tvPower').textContent=item.tvOn?'On':'Off';document.getElementById('customerName').value=item.player==='Available'?'':item.player;var gameSelect=document.getElementById('gameSelect');Array.from(gameSelect.options).forEach(function(option){option.selected=option.value===item.game});document.querySelector('[data-station-action="wake"]').disabled=!isStandby;['pause','add','message','standby'].forEach(function(action){document.querySelector('[data-station-action="'+action+'"]').disabled=!isActive});document.querySelector('[data-station-action="pause"]').textContent=item.paused?'Resume session':'Pause session';document.getElementById('paymentsList').innerHTML=isActive?'<div class="payment-row"><div><b>Current session</b><small>'+escapeHtml(item.player)+' · '+(item.paid?'payment recorded':'payment pending')+'</small></div><div><b>'+item.price+'</b><br><button data-station-pay>'+(item.paid?'Mark unpaid':'Mark paid')+'</button></div></div><div class="payment-row"><div><b>Previous session</b><small>'+item.name+' · wallet</small></div><b>'+(/PS5/.test(item.type)?'25 MAD':'15 MAD')+'</b></div>':'<div class="payment-row"><div><b>No active payment</b><small>'+item.name+' is '+item.status.toLowerCase()+'</small></div><b>—</b></div>';var payButton=document.querySelector('[data-station-pay]');if(payButton)payButton.addEventListener('click',function(){item.paid=!item.paid;selectStation(index);showToast('Session payment marked '+(item.paid?'paid':'unpaid'))});var history=[{title:isActive?'Session active':item.status,detail:isActive?item.player+' · '+item.game:item.name+' · no active customer',when:'Now'}].concat(item.history.map(function(entry){return{title:entry.split(' · ')[0],detail:entry,when:'Done'}}));document.getElementById('historyList').innerHTML=history.slice(0,5).map(function(entry){return '<div class="history-row"><div><b>'+escapeHtml(entry.title)+'</b><small>'+escapeHtml(entry.detail)+'</small></div><span>'+entry.when+'</span></div>'}).join('')}
  function syncOverview(index){if(!window._ssT||Date.now()-window._ssT>5000){window._ssT=Date.now();demoStore.set('stations',stationData)}var item=stationData[index],card=cards[index];card.dataset.player=item.player;card.dataset.game=item.game;card.dataset.time=item.time;card.querySelector('.status').textContent=item.status;card.querySelector('.status').className='status'+(item.status==='Playing'?' active':(item.status.indexOf('min')>-1?' warning':''));card.querySelector('.timer-row strong').textContent=item.time;card.querySelector('.timer-row small').textContent=displayState(item);card.querySelector('.player span').innerHTML='<b>'+escapeHtml(item.player)+'</b><br>'+escapeHtml(item.game);card.querySelector('.player > b').textContent=item.price}
  function runStationAction(index,action){var item=stationData[index],isActive=activeSession(item);if(action==='tv'){item.tvOn=!item.tvOn;item.history.unshift('TV turned '+(item.tvOn?'on':'off')+' · Remote command');showToast(item.name+' TV turned '+(item.tvOn?'on':'off'))}else if(action==='standby'){if(!isActive){showToast('No active session to end');return}item.status='Standby';item.time='Standby';item.elapsed=0;item.remaining=0;item.state='Wake remotely';item.player='Available';item.game='Standby';item.paused=false;item.tvOn=false;item.history.unshift('Session ended · Console in standby');showToast(item.name+' session ended and console set to standby')}else if(action==='wake'){if(item.time!=='Standby'){showToast(item.name+' is already online');return}item.status='Ready';item.time='Ready';item.state='Online';item.player='Available';item.game='No active session';item.tvOn=true;item.history.unshift('Console woken · Ready for session');showToast(item.name+' is ready')}else if(action==='pause'){if(!isActive){showToast('No active session to pause');return}item.paused=!item.paused;item.history.unshift((item.paused?'Session paused':'Session resumed')+' · Staff control');showToast(item.paused?'Session paused':'Session resumed')}else if(action==='add'){if(!isActive){showToast('No active countdown to extend');return}item.remaining+=900;item.state=Math.ceil(item.remaining/60)+' min left';item.history.unshift('15 minutes added · Session extended');showToast('15 minutes added to '+item.name)}else if(action==='message'){if(!isActive){showToast('No active customer to notify');return}item.history.unshift('Time warning sent · Customer notified');showToast('Time warning sent to '+item.name)}syncOverview(index);renderRail();if(selectedIndex===index)selectStation(index);if(drawer.classList.contains('open')&&drawerIndex===index)refreshDrawer()}
  renderRail();selectStation(0);

  document.querySelectorAll('.console-tab').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.console-tab').forEach(function(tab){tab.classList.toggle('active',tab===btn)});document.querySelectorAll('.tab-panel').forEach(function(panel){panel.classList.toggle('active',panel.dataset.panel===btn.dataset.tab)})})});
  function openTab(name){var tab=document.querySelector('.console-tab[data-tab="'+name+'"]');if(tab)tab.click()}
  document.querySelectorAll('[data-station-action]').forEach(function(btn){btn.addEventListener('click',function(){runStationAction(selectedIndex,btn.dataset.stationAction)})});
  document.querySelectorAll('[data-action]').forEach(function(btn){btn.addEventListener('click',function(){var map={Wake:'wake',TV:'tv','Add 15 minutes':'add',Standby:'standby'};runStationAction(drawerIndex,map[btn.dataset.action])})});

  function updateTotal(){var minutes=Number(document.getElementById('durationSelect').value),rate=Number(document.getElementById('rateSelect').value);document.getElementById('sessionTotal').textContent=Math.round(minutes/60*rate)+' MAD'}
  document.getElementById('durationSelect').addEventListener('change',updateTotal);document.getElementById('rateSelect').addEventListener('change',updateTotal);
  document.getElementById('clearSession').addEventListener('click',function(){document.getElementById('customerName').value='';showToast('Session form cleared')});
  document.getElementById('previewSession').addEventListener('click',function(){var customer=document.getElementById('customerName').value.trim();if(!customer){showToast('Add a customer name first');return}var item=stationData[selectedIndex],minutes=Number(document.getElementById('durationSelect').value),amount=Math.round(minutes/60*Number(document.getElementById('rateSelect').value));item.player=customer;item.game=document.getElementById('gameSelect').value;item.status='Playing';item.time='00:00:00';item.elapsed=0;item.remaining=minutes*60;item.state=minutes+' min left';item.price=amount+' MAD';item.paid=false;item.paused=false;item.tvOn=true;item.history.unshift('Session started · '+customer);transactions.unshift({customer:customer,detail:item.name+' · Cash',amount:amount,status:'Pending',time:new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})});renderTransactions();syncOverview(selectedIndex);selectStation(selectedIndex);openTab('control');showToast('Session started with a pending payment')});

  function newSession(){var index=stationData.findIndex(function(item){return item.time==='Ready'});if(index<0)index=stationData.findIndex(function(item){return item.time==='Standby'});showView('stations');selectStation(index<0?0:index);openTab('session');showToast('New session preview opened')}
  document.getElementById('quickStart').addEventListener('click',newSession);document.getElementById('mobileAdd').addEventListener('click',newSession);

  var bracketInitial=[{players:['Youssef A.','Mehdi R.'],winner:'Youssef A.',score:['3','1']},{players:['Omar B.','Hamza K.'],winner:'Omar B.',score:['2','0']},{players:['Karim S.','Amine L.'],winner:null,score:['1','1']},{players:['Anas M.','Zakaria T.'],winner:null,score:['—','—']}];
  var bracketState={qf:bracketInitial.map(function(match){return{players:match.players.slice(),winner:match.winner,score:match.score.slice()}}),sf:[{winner:null},{winner:null}],finalWinner:null};
  function bracketRounds(){return{qf:bracketState.qf,sf:[{players:[bracketState.qf[0].winner,bracketState.qf[1].winner],winner:bracketState.sf[0].winner},{players:[bracketState.qf[2].winner,bracketState.qf[3].winner],winner:bracketState.sf[1].winner}],final:[{players:[bracketState.sf[0].winner,bracketState.sf[1].winner],winner:bracketState.finalWinner}]}}
  function firstOpenMatch(rounds){var order=[['qf','Quarter-final'],['sf','Semi-final'],['final','Final']];for(var r=0;r<order.length;r++){var stage=order[r][0];for(var i=0;i<rounds[stage].length;i++){var match=rounds[stage][i];if(match.players[0]&&match.players[1]&&!match.winner)return{stage:stage,index:i,label:order[r][1]+' '+(i+1),players:match.players}}}return null}
  function roadMatchMarkup(stage,index,match,current){var ready=match.players[0]&&match.players[1],done=!!match.winner,classes='road-match'+(stage==='final'?' final-match':'')+(done?' done':'')+(current&&current.stage===stage&&current.index===index?' current':'');var status=done?'Winner advanced':(ready?(current&&current.stage===stage&&current.index===index?'Current':'Ready'):'Waiting for winners');var rows=match.players.map(function(player,playerIndex){var name=player||'Awaiting previous winner',winner=player&&player===match.winner,score=match.score?match.score[playerIndex]:(winner?'✓':'—');return '<button class="road-player '+(winner?'winner':(!player?'pending':''))+'" '+((!ready||done)?'disabled':'')+' data-bracket-stage="'+stage+'" data-bracket-index="'+index+'" data-bracket-player="'+playerIndex+'"><span>'+escapeHtml(name)+'</span><span class="road-score">'+score+'</span></button>'}).join('');return '<div class="'+classes+'"><div class="match-kicker"><span>Match '+(index+1)+'</span><b>'+status+'</b></div>'+rows+'</div>'}
  function renderBracket(){var rounds=bracketRounds(),current=firstOpenMatch(rounds),road=document.getElementById('bracketRoad');var stages=[{key:'qf',title:'QUARTER-FINALS',note:'4 winners feed the semi-finals'},{key:'sf',title:'SEMI-FINALS',note:'2 winners feed the final'},{key:'final',title:'FINAL',note:'Winner becomes champion'}];road.innerHTML=stages.map(function(stage){return '<section class="bracket-stage '+(stage.key==='sf'?'semifinal':stage.key==='final'?'final':'')+'"><h4>'+stage.title+'</h4><div class="stage-note">'+stage.note+'</div>'+rounds[stage.key].map(function(match,index){return roadMatchMarkup(stage.key,index,match,current)}).join('')+'</section>'}).join('');var completed=bracketState.qf.filter(function(match){return match.winner}).length+bracketState.sf.filter(function(match){return match.winner}).length+(bracketState.finalWinner?1:0);document.getElementById('bracketProgress').textContent=completed+' / 7';document.getElementById('bracketTrack').style.width=Math.round(completed/7*100)+'%';var champion=document.getElementById('championCard');champion.classList.toggle('show',!!bracketState.finalWinner);document.getElementById('championName').textContent=bracketState.finalWinner||'—';var nextText=current?current.players.join(' vs ')+' · '+current.label.toLowerCase():'Tournament complete · '+bracketState.finalWinner+' is champion';document.getElementById('nextMatchText').textContent=nextText;document.getElementById('attentionMatch').textContent=current?current.players.join(' vs '):bracketState.finalWinner+' wins the cup';document.getElementById('attentionDetail').innerHTML=current?current.label+' <span>· choose the winner in the road above</span>':'All rounds complete <span>· champion confirmed</span>';road.querySelectorAll('[data-bracket-stage]').forEach(function(btn){btn.addEventListener('click',function(){setBracketWinner(btn.dataset.bracketStage,Number(btn.dataset.bracketIndex),Number(btn.dataset.bracketPlayer))})})}
  function setBracketWinner(stage,index,playerIndex){var rounds=bracketRounds(),player=rounds[stage][index].players[playerIndex];if(!player)return;if(stage==='qf'){bracketState.qf[index].winner=player;bracketState.sf[index<2?0:1].winner=null;bracketState.finalWinner=null}else if(stage==='sf'){bracketState.sf[index].winner=player;bracketState.finalWinner=null}else{bracketState.finalWinner=player}renderBracket();showToast(player+' advances to the '+(stage==='qf'?'semi-final':stage==='sf'?'final':'championship'))}
  document.getElementById('resetBracket').addEventListener('click',function(){bracketState={qf:bracketInitial.map(function(match){return{players:match.players.slice(),winner:match.winner,score:match.score.slice()}}),sf:[{winner:null},{winner:null}],finalWinner:null};renderBracket();showToast('Tournament road reset to the current demo round')});renderBracket();
  document.querySelectorAll('[data-result]').forEach(function(btn){btn.addEventListener('click',function(){showView('competition');setBoardTab('knockout');showToast('Enter both scores beside the match')})});
  function togglePanel(id,open){document.getElementById(id).classList.toggle('open',open)}
  var customerParticipantNames=['Youssef Amrani','Omar Bennani','Hassan Mansouri','Karim Saidi','Salma Rahmani','Mehdi Rami','Amine Lakhdar','Rania Khalfi'];
  var tournamentParticipants=[];
  (function(s){if(Array.isArray(s))tournamentParticipants=s;})(demoStore.get('tournamentParticipants'));
  function syncParticipantOptions(){var select=document.getElementById('customerParticipant');select.innerHTML='<option value="">Choose from customer list</option>'+customerParticipantNames.filter(function(name){return tournamentParticipants.indexOf(name)<0}).map(function(name){return '<option>'+escapeHtml(name)+'</option>'}).join('')}
  function renderTournamentRoster(){var roster=document.getElementById('tournamentRoster');roster.innerHTML=tournamentParticipants.map(function(name,index){return '<span class="roster-chip">'+escapeHtml(name)+'<button aria-label="Remove '+escapeHtml(name)+'" data-remove-participant="'+index+'">×</button></span>'}).join('');document.getElementById('rosterCount').textContent=tournamentParticipants.length+' player'+(tournamentParticipants.length===1?'':'s')+' added · use 4 to 8 for this demo bracket';roster.querySelectorAll('[data-remove-participant]').forEach(function(btn){btn.addEventListener('click',function(){tournamentParticipants.splice(Number(btn.dataset.removeParticipant),1);renderTournamentRoster();syncParticipantOptions()})});syncParticipantOptions()}
  function addTournamentParticipant(name){name=name.trim();if(!name){showToast('Choose or type a player name');return}if(tournamentParticipants.some(function(item){return item.toLowerCase()===name.toLowerCase()})){showToast('That player is already in the roster');return}if(tournamentParticipants.length>=8){showToast('This demo bracket supports up to 8 players');return}tournamentParticipants.push(name);renderTournamentRoster()}
  function updateTournamentFormat(){var format=document.getElementById('eventFormat').value,groupField=document.getElementById('eventGroupSize').closest('.field'),hint=document.getElementById('formatHint');groupField.style.display=format==='knockout'?'none':'grid';hint.innerHTML=format==='knockout'?'<b>Knockout:</b> players enter a direct elimination bracket. Winners advance automatically when scores are saved.':format==='groups'?'<b>Group stage + knockout:</b> group tables update from match scores, then the top two in each group move to the knockout stage.':'<b>Round robin:</b> every player meets every other player and the table ranks them by points and goal difference.'}
  document.getElementById('eventFormat').addEventListener('change',updateTournamentFormat);document.getElementById('addCustomerParticipant').addEventListener('click',function(){addTournamentParticipant(document.getElementById('customerParticipant').value)});document.getElementById('addManualParticipant').addEventListener('click',function(){var input=document.getElementById('manualParticipant');addTournamentParticipant(input.value);input.value=''});document.getElementById('manualParticipant').addEventListener('keydown',function(event){if(event.key==='Enter'){event.preventDefault();document.getElementById('addManualParticipant').click()}});renderTournamentRoster();updateTournamentFormat();

  var boardEvent={name:'FC 26 Friday Cup',game:'EA Sports FC 26',format:'knockout',date:'2026-10-02T20:00',entry:100,players:['Youssef Amrani','Mehdi Rami','Omar Bennani','Hamza K.','Karim Saidi','Amine Lakhdar','Anas M.','Zakaria T.']};
  (function(s){if(s&&s.name)boardEvent=s;})(demoStore.get('boardEvent'));
  var groupFixtures=[],detailState=null;
  (function(s){if(Array.isArray(s))groupFixtures=s;})(demoStore.get('groupFixtures'));
  function resetBoardData(){var players=boardEvent.players.slice(0,8);while(players.length<8)players.push('BYE '+(players.length+1));var groups=[players.filter(function(_,i){return i%2===0}),players.filter(function(_,i){return i%2===1})];groupFixtures=[];groups.forEach(function(group,groupIndex){for(var i=0;i<group.length;i++)for(var j=i+1;j<group.length;j++)groupFixtures.push({group:groupIndex,a:group[i],b:group[j],sa:null,sb:null})});if(boardEvent.name==='FC 26 Friday Cup'){var preset=[[3,1],[2,2],[2,0],[1,1]];groupFixtures.filter(function(_,i){return i<4}).forEach(function(match,i){match.sa=preset[i][0];match.sb=preset[i][1]})}detailState={qf:[],sf:[{players:[null,null],winner:null,score:[null,null]},{players:[null,null],winner:null,score:[null,null]}],final:{players:[null,null],winner:null,score:[null,null]}};for(var q=0;q<4;q++)detailState.qf.push({players:[players[q*2],players[q*2+1]],winner:null,score:[null,null]});if(boardEvent.name==='FC 26 Friday Cup'){detailState.qf[0].score=[3,1];detailState.qf[0].winner=detailState.qf[0].players[0];detailState.qf[1].score=[2,0];detailState.qf[1].winner=detailState.qf[1].players[0]}syncDetailProgression()}
  function calculateStandings(groupIndex){var names=boardEvent.players.slice(0,8).filter(function(_,i){return i%2===groupIndex}),rows=names.map(function(name){return{name:name,p:0,w:0,d:0,l:0,gf:0,ga:0,pts:0}});groupFixtures.filter(function(match){return match.group===groupIndex&&match.sa!==null&&match.sb!==null}).forEach(function(match){var a=rows.find(function(row){return row.name===match.a}),b=rows.find(function(row){return row.name===match.b});if(!a||!b)return;a.p++;b.p++;a.gf+=match.sa;a.ga+=match.sb;b.gf+=match.sb;b.ga+=match.sa;if(match.sa>match.sb){a.w++;b.l++;a.pts+=3}else if(match.sb>match.sa){b.w++;a.l++;b.pts+=3}else{a.d++;b.d++;a.pts++;b.pts++}});return rows.sort(function(a,b){return b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf})}
  function renderGroups(){demoStore.set('groupFixtures',groupFixtures);var grid=document.getElementById('groupGrid'),groups=[0,1];grid.innerHTML=groups.map(function(groupIndex){var rows=calculateStandings(groupIndex),fixtures=groupFixtures.map(function(item,index){return{item:item,index:index}}).filter(function(entry){return entry.item.group===groupIndex});return '<article class="group-card"><h3>'+(boardEvent.format==='round-robin'?'League table':'Group '+String.fromCharCode(65+groupIndex))+'</h3><p>3 points for a win · 1 for a draw · top two highlighted</p><table class="group-table"><thead><tr><th>#</th><th>Player</th><th>P</th><th>W</th><th>D</th><th>GD</th><th>Pts</th></tr></thead><tbody>'+rows.map(function(row,index){return '<tr><td>'+(index+1)+'</td><td><b>'+(index<2?'● ':'')+escapeHtml(row.name)+'</b></td><td>'+row.p+'</td><td>'+row.w+'</td><td>'+row.d+'</td><td>'+((row.gf-row.ga)>0?'+':'')+(row.gf-row.ga)+'</td><td><b>'+row.pts+'</b></td></tr>'}).join('')+'</tbody></table><div class="fixture-list">'+fixtures.map(function(entry){var match=entry.item;return '<div class="fixture"><div><b>'+escapeHtml(match.a)+' vs '+escapeHtml(match.b)+'</b><small>'+(match.sa===null?'Awaiting score':'Saved · '+match.sa+'–'+match.sb)+'</small></div><div class="fixture-score"><input type="number" min="0" value="'+(match.sa===null?'':match.sa)+'" aria-label="'+escapeHtml(match.a)+' score" data-group-score-a="'+entry.index+'"><span>–</span><input type="number" min="0" value="'+(match.sb===null?'':match.sb)+'" aria-label="'+escapeHtml(match.b)+' score" data-group-score-b="'+entry.index+'"><button data-save-group-score="'+entry.index+'">Save</button></div></div>'}).join('')+'</div></article>'}).join('');grid.querySelectorAll('[data-save-group-score]').forEach(function(btn){btn.addEventListener('click',function(){var index=Number(btn.dataset.saveGroupScore),a=grid.querySelector('[data-group-score-a="'+index+'"]'),b=grid.querySelector('[data-group-score-b="'+index+'"]');if(a.value===''||b.value===''||Number(a.value)<0||Number(b.value)<0){showToast('Enter both non-negative scores');return}groupFixtures[index].sa=Number(a.value);groupFixtures[index].sb=Number(b.value);renderGroups();updateBoardStats();showToast('Group score saved and table updated')})})}
  function syncDetailProgression(){detailState.sf[0].players=[detailState.qf[0].winner,detailState.qf[1].winner];detailState.sf[1].players=[detailState.qf[2].winner,detailState.qf[3].winner];if(detailState.sf[0].winner&&detailState.sf[0].players.indexOf(detailState.sf[0].winner)<0){detailState.sf[0].winner=null;detailState.sf[0].score=[null,null]}if(detailState.sf[1].winner&&detailState.sf[1].players.indexOf(detailState.sf[1].winner)<0){detailState.sf[1].winner=null;detailState.sf[1].score=[null,null]}detailState.final.players=[detailState.sf[0].winner,detailState.sf[1].winner];if(detailState.final.winner&&detailState.final.players.indexOf(detailState.final.winner)<0){detailState.final.winner=null;detailState.final.score=[null,null]}}
  var activeRound='qf';
  function playerInitials(name){if(!name)return '—';return name.split(/\s+/).map(function(part){return part.charAt(0)}).slice(0,2).join('').toUpperCase()}
  function detailMatchMarkup(stage,index,match,current){var ready=match.players[0]&&match.players[1],done=!!match.winner,isLive=!!(current&&current.stage===stage&&current.index===index),status=done?'FT':isLive?'LIVE':'UPCOMING',statusClass=done?'ft':isLive?'live':'upcoming',date=new Date(boardEvent.date),dateLabel=date.toLocaleDateString('en-GB',{day:'numeric',month:'short'})+' · '+(stage==='qf'?String(date.getHours()).padStart(2,'0')+':'+String(date.getMinutes()).padStart(2,'0'):'TBD');return '<div class="detail-match '+(stage==='final'?'last ':'')+(done?'done ':isLive?'live ':'')+'" data-match-card="'+stage+'-'+index+'"><div class="detail-match-head"><span>'+dateLabel+'</span><span class="match-status '+statusClass+'">'+status+'</span></div>'+match.players.map(function(player,i){return '<label class="score-player '+(player&&player===match.winner?'winner':'')+'"><span class="player-avatar">'+escapeHtml(playerInitials(player))+'</span><span>'+escapeHtml(player||'Awaiting winner')+'</span><input type="number" min="0" '+(ready?'':'disabled')+' value="'+(match.score[i]===null?'':match.score[i])+'" placeholder="—" aria-label="'+escapeHtml(player||'Pending player')+' score" data-detail-score="'+stage+'-'+index+'-'+i+'"></label>'}).join('')+'<button class="save-score" '+(ready?'':'disabled')+' data-save-detail="'+stage+'-'+index+'">'+(done?'Update result':ready?'Save score':'Waiting for winners')+'</button></div>'}
  function findCurrentDetailMatch(){var rounds=[{stage:'qf',matches:detailState.qf},{stage:'sf',matches:detailState.sf},{stage:'final',matches:[detailState.final]}];for(var r=0;r<rounds.length;r++){for(var i=0;i<rounds[r].matches.length;i++){var match=rounds[r].matches[i];if(match.players[0]&&match.players[1]&&!match.winner)return{stage:rounds[r].stage,index:i}}}return null}
  function syncRoundNavigator(){var order=['qf','sf','final'];document.querySelectorAll('[data-round-tab]').forEach(function(btn){btn.classList.toggle('active',btn.dataset.roundTab===activeRound)});document.querySelectorAll('.detail-round').forEach(function(round){round.classList.toggle('round-visible',round.dataset.round===activeRound)});document.getElementById('previousRound').disabled=order.indexOf(activeRound)===0;document.getElementById('nextRound').disabled=order.indexOf(activeRound)===order.length-1}
  function drawBracketConnectors(root){var svg=root.querySelector('.bracket-connectors');if(!svg||window.innerWidth<=760)return;var box=root.getBoundingClientRect(),pairs=[['qf-0','sf-0'],['qf-1','sf-0'],['qf-2','sf-1'],['qf-3','sf-1'],['sf-0','final-0'],['sf-1','final-0']];var paths=pairs.map(function(pair){var a=root.querySelector('[data-match-card="'+pair[0]+'"]'),b=root.querySelector('[data-match-card="'+pair[1]+'"]');if(!a||!b)return'';var ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),x1=ar.right-box.left,y1=ar.top-box.top+ar.height/2,x2=br.left-box.left,y2=br.top-box.top+br.height/2,mid=(x1+x2)/2,live=a.classList.contains('live')||b.classList.contains('live');return '<path class="'+(live?'live-path':'')+'" d="M '+x1+' '+y1+' H '+mid+' V '+y2+' H '+x2+'"/>'}).join('');svg.setAttribute('viewBox','0 0 '+box.width+' '+box.height);svg.innerHTML=paths}
  function renderDetailBracket(){syncDetailProgression();var current=findCurrentDetailMatch(),rounds=[{key:'qf',title:'QUARTER-FINALS',matches:detailState.qf},{key:'sf',title:'SEMI-FINALS',matches:detailState.sf},{key:'final',title:'FINAL',matches:[detailState.final]}],root=document.getElementById('detailBracket');root.innerHTML='<svg class="bracket-connectors" aria-hidden="true"></svg>'+rounds.map(function(round){return '<section class="detail-round" data-round="'+round.key+'"><h3>'+round.title+'</h3>'+round.matches.map(function(match,index){return detailMatchMarkup(round.key,index,match,current)}).join('')+'</section>'}).join('');requestAnimationFrame(function(){drawBracketConnectors(root)});root.querySelectorAll('[data-save-detail]').forEach(function(btn){btn.addEventListener('click',function(){var parts=btn.dataset.saveDetail.split('-'),stage=parts[0],index=Number(parts[1]),match=stage==='qf'?detailState.qf[index]:stage==='sf'?detailState.sf[index]:detailState.final,a=root.querySelector('[data-detail-score="'+stage+'-'+index+'-0"]'),b=root.querySelector('[data-detail-score="'+stage+'-'+index+'-1"]');if(a.value===''||b.value===''){showToast('Enter both scores');return}var sa=Number(a.value),sb=Number(b.value);if(sa===sb){showToast('Knockout matches need a winner — break the tie');return}if(sa<0||sb<0){showToast('Scores cannot be negative');return}match.score=[sa,sb];match.winner=match.players[sa>sb?0:1];if(stage==='qf'){detailState.sf[index<2?0:1].winner=null;detailState.sf[index<2?0:1].score=[null,null];detailState.final.winner=null;detailState.final.score=[null,null]}else if(stage==='sf'){detailState.final.winner=null;detailState.final.score=[null,null]}activeRound=stage==='qf'?'sf':stage==='sf'?'final':'final';renderDetailBracket();updateBoardStats();showToast(match.winner+' advances')})});var champion=document.getElementById('detailChampion');champion.classList.toggle('show',!!detailState.final.winner);document.getElementById('detailChampionName').textContent=detailState.final.winner||'—';syncRoundNavigator()}
  function updateBoardStats(){document.getElementById('groupMatchesPlayed').textContent=boardEvent.format==='knockout'?'—':groupFixtures.filter(function(match){return match.sa!==null}).length+' / '+groupFixtures.length;var complete=detailState.qf.filter(function(match){return match.winner}).length+detailState.sf.filter(function(match){return match.winner}).length+(detailState.final.winner?1:0);document.getElementById('knockoutMatchesPlayed').textContent=boardEvent.format==='round-robin'?'—':complete+' / 7';document.getElementById('boardStatus').textContent=detailState.final.winner?'Complete':'In progress'}
  function setBoardTab(name){document.querySelectorAll('[data-board-tab]').forEach(function(btn){btn.classList.toggle('active',btn.dataset.boardTab===name)});document.querySelectorAll('[data-board-panel]').forEach(function(panel){panel.classList.toggle('active',panel.dataset.boardPanel===name)})}
  function renderTournamentBoard(){demoStore.set('boardEvent',boardEvent);demoStore.set('groupFixtures',groupFixtures);demoStore.set('tournamentParticipants',tournamentParticipants);demoStore.set('tournamentHistory',tournamentHistory);var date=new Date(boardEvent.date);document.getElementById('boardTitle').textContent=boardEvent.name;document.getElementById('boardGame').textContent=boardEvent.game;document.getElementById('boardDate').textContent=date.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})+' · '+String(date.getHours()).padStart(2,'0')+':'+String(date.getMinutes()).padStart(2,'0');document.getElementById('boardEntry').textContent=boardEvent.entry+' MAD';document.getElementById('boardPlayerCount').textContent=boardEvent.players.length;var formatLabel=boardEvent.format==='groups'?'Group stage + knockout':boardEvent.format==='round-robin'?'Round robin':'Knockout';document.getElementById('boardSubtitle').textContent=formatLabel+' · '+boardEvent.players.length+' players · scores and progression update here.';var groupsButton=document.querySelector('[data-board-tab="groups"]'),knockoutButton=document.querySelector('[data-board-tab="knockout"]');groupsButton.style.display=boardEvent.format==='knockout'?'none':'inline-block';knockoutButton.style.display=boardEvent.format==='round-robin'?'none':'inline-block';activeRound='qf';resetBoardData();renderGroups();renderDetailBracket();updateBoardStats();setBoardTab(boardEvent.format==='knockout'?'knockout':'groups')}
  function openNewTournamentForm(){tournamentParticipants=[];renderTournamentRoster();document.getElementById('manualParticipant').value='';showView('tournaments');togglePanel('tournamentForm',true);document.getElementById('tournamentForm').scrollIntoView({behavior:'smooth',block:'center'})}
  var tournamentHistory=[{name:'FC 26 Summer Final',game:'EA Sports FC 26',date:'18 Sep 2026',champion:'Omar Bennani',runner:'Youssef Amrani',score:'4–2',rounds:['QF: 3–0, 2–1, 4–3, 1–0','SF: 2–1, 3–2','Final: 4–2']},{name:'Tekken 8 Night',game:'Tekken 8',date:'28 Aug 2026',champion:'Salma Rahmani',runner:'Karim Saidi',score:'3–1',rounds:['QF: 2–0, 2–1, 2–0, 2–1','SF: 2–1, 2–0','Final: 3–1']},{name:'eFootball July Cup',game:'eFootball',date:'24 Jul 2026',champion:'Mehdi Rami',runner:'Amine Lakhdar',score:'2–0',rounds:['QF: 3–2, 1–0, 4–1, 2–1','SF: 2–1, 3–0','Final: 2–0']},{name:'FC 26 June Knockout',game:'EA Sports FC 26',date:'19 Jun 2026',champion:'Youssef Amrani',runner:'Hamza K.',score:'3–2',rounds:['QF: 2–0, 3–1, 1–0, 4–2','SF: 2–1, 2–0','Final: 3–2']}];
  (function(s){if(Array.isArray(s)&&s.length)tournamentHistory=s;})(demoStore.get('tournamentHistory'));
  function renderTournamentHistory(){var root=document.getElementById('tournamentHistory');root.innerHTML=tournamentHistory.map(function(item,index){return '<article class="history-item"><button class="history-toggle" data-history="'+index+'" aria-expanded="false"><span><small>TOURNAMENT</small><b>'+escapeHtml(item.name)+'</b></span><span><small>CHAMPION</small><b>'+escapeHtml(item.champion)+'</b></span><span><small>RUNNER-UP</small><b>'+escapeHtml(item.runner)+'</b></span><span><small>FINAL</small><b>'+item.score+'</b></span><span><small>DATE · GAME</small><b>'+item.date+' · '+escapeHtml(item.game)+'</b></span><span class="history-chevron">›</span></button><div class="history-detail"><div class="history-final"><div class="history-final-player winner"><span>'+escapeHtml(playerInitials(item.champion))+'</span><b>'+escapeHtml(item.champion)+'</b><small>Champion</small></div><div class="history-final-score">'+item.score+'<small>Full time</small></div><div class="history-final-player"><span>'+escapeHtml(playerInitials(item.runner))+'</span><b>'+escapeHtml(item.runner)+'</b><small>Runner-up</small></div></div><div class="history-rounds">'+item.rounds.map(function(round){return '<span>'+round+'</span>'}).join('')+'</div></div></article>'}).join('');root.querySelectorAll('[data-history]').forEach(function(btn){btn.addEventListener('click',function(){var item=btn.closest('.history-item'),open=!item.classList.contains('open');root.querySelectorAll('.history-item').forEach(function(row){row.classList.remove('open');row.querySelector('.history-toggle').setAttribute('aria-expanded','false')});if(open){item.classList.add('open');btn.setAttribute('aria-expanded','true')}})})}
  document.querySelectorAll('[data-board-tab]').forEach(function(btn){btn.addEventListener('click',function(){setBoardTab(btn.dataset.boardTab)})});document.querySelectorAll('[data-round-tab]').forEach(function(btn){btn.addEventListener('click',function(){activeRound=btn.dataset.roundTab;syncRoundNavigator()})});document.getElementById('previousRound').addEventListener('click',function(){var order=['qf','sf','final'],index=order.indexOf(activeRound);if(index>0){activeRound=order[index-1];syncRoundNavigator()}});document.getElementById('nextRound').addEventListener('click',function(){var order=['qf','sf','final'],index=order.indexOf(activeRound);if(index<order.length-1){activeRound=order[index+1];syncRoundNavigator()}});renderTournamentHistory();document.getElementById('openTournamentBoard').addEventListener('click',function(){showView('competition')});document.getElementById('backTournaments').addEventListener('click',function(){showView('tournaments')});document.getElementById('boardNewTournament').addEventListener('click',openNewTournamentForm);document.getElementById('resetDetailBracket').addEventListener('click',function(){activeRound='qf';resetBoardData();renderDetailBracket();updateBoardStats();showToast('Knockout scores reset')});renderTournamentBoard();

  document.getElementById('newTournament').addEventListener('click',openNewTournamentForm);
  document.getElementById('closeTournamentForm').addEventListener('click',function(){togglePanel('tournamentForm',false)});document.getElementById('cancelTournament').addEventListener('click',function(){togglePanel('tournamentForm',false)});
  function shuffleDraw(list){for(var i=list.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),t=list[i];list[i]=list[j];list[j]=t}return list}
  document.getElementById('saveTournament').addEventListener('click',function(){var name=document.getElementById('eventName').value.trim(),dateValue=document.getElementById('eventDate').value;if(!name||!dateValue||tournamentParticipants.length<4){showToast('Add a name, date and at least 4 players');return}boardEvent={name:name,game:document.getElementById('eventGame').value,format:document.getElementById('eventFormat').value,date:dateValue,entry:Number(document.getElementById('eventEntry').value)||0,players:shuffleDraw(tournamentParticipants.slice())};var date=new Date(dateValue),day=String(date.getDate()).padStart(2,'0'),month=date.toLocaleDateString('en-GB',{month:'short'}),time=String(date.getHours()).padStart(2,'0')+':'+String(date.getMinutes()).padStart(2,'0'),formatLabel=boardEvent.format==='groups'?'Group stage + knockout':boardEvent.format==='round-robin'?'Round robin':'Knockout',row=document.createElement('div');row.className='upcoming';row.innerHTML='<div class="date-block"><strong>'+day+'</strong><span>'+month+'</span></div><div><b>'+escapeHtml(name)+'</b><small>'+formatLabel+' · '+tournamentParticipants.length+' players</small></div><button class="match-action" data-open-created>Open</button>';row.querySelector('[data-open-created]').addEventListener('click',function(){showView('competition')});document.getElementById('upcomingList').prepend(row);document.getElementById('eventCount').textContent=Number(document.getElementById('eventCount').textContent)+1;togglePanel('tournamentForm',false);renderTournamentBoard();showView('competition');showToast('Tournament created — board ready for scores')});

  function escapeHtml(value){return String(value).replace(/[&<>'"]/g,function(character){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]})}
  var reservations=[{name:'Salma R.',console:'PlayStation 5',time:'18:30',duration:'2 hours',status:'Confirmed'},{name:'Anas M.',console:'PlayStation 4',time:'19:00',duration:'1 hour',status:'Confirmed'},{name:'Rania K.',console:'Any available',time:'19:30',duration:'2 hours',status:'Arrived'},{name:'Mehdi R.',console:'PlayStation 5',time:'20:00',duration:'1 hour',status:'Waitlist'},{name:'Hamza K.',console:'PlayStation 5',time:'20:00',duration:'2 hours',status:'Waitlist'}],editingReservation=-1;
  (function(s){if(Array.isArray(s))reservations=s;})(demoStore.get('reservations'));
  function openReservationForm(index){editingReservation=typeof index==='number'?index:-1;var item=editingReservation>-1?reservations[editingReservation]:{name:'',console:'PlayStation 5',time:'21:00',duration:'2 hours'};document.getElementById('reservationName').value=item.name;document.getElementById('reservationConsole').value=item.console;document.getElementById('reservationTime').value=item.time;document.getElementById('reservationDuration').value=item.duration;document.getElementById('reservationFormTitle').textContent=editingReservation>-1?'Edit reservation':'Add reservation';document.getElementById('saveReservation').textContent=editingReservation>-1?'Save changes':'Add reservation';togglePanel('reservationForm',true);document.getElementById('reservationForm').scrollIntoView({behavior:'smooth',block:'center'})}
  function renderReservations(){demoStore.set('reservations',reservations);var filter=document.getElementById('reservationFilter').value,list=document.getElementById('reservationList'),visible=reservations.map(function(item,index){return{item:item,index:index}}).filter(function(entry){return filter==='all'||entry.item.status===filter});list.innerHTML=visible.map(function(entry){var item=entry.item;return '<article class="list-row"><div><p><b>'+escapeHtml(item.name)+'</b></p><small>'+escapeHtml(item.console)+' · '+escapeHtml(item.duration)+'</small></div><div><span class="row-label">Arrival</span><b>'+escapeHtml(item.time)+'</b></div><div><span class="row-label">Status</span><span class="status-chip">'+escapeHtml(item.status)+'</span></div><div><span class="row-label">Booking</span><b>Today</b></div><div class="row-actions"><button data-res-action="edit" data-index="'+entry.index+'">Edit</button><button data-res-action="arrive" data-index="'+entry.index+'">Arrived</button><button data-res-action="confirm" data-index="'+entry.index+'">Confirm</button><button class="danger" data-res-action="cancel" data-index="'+entry.index+'">Cancel</button></div></article>'}).join('');document.getElementById('reservationEmpty').style.display=visible.length?'none':'block';document.getElementById('reservationToday').textContent=reservations.length;list.querySelectorAll('[data-res-action]').forEach(function(btn){btn.addEventListener('click',function(){var index=Number(btn.dataset.index),action=btn.dataset.resAction;if(action==='edit'){openReservationForm(index);return}if(action==='cancel'){reservations.splice(index,1);showToast('Reservation cancelled in the demo')}else{reservations[index].status=action==='arrive'?'Arrived':'Confirmed';showToast(action==='arrive'?'Guest marked arrived':'Reservation confirmed')}renderReservations()})})}
  document.getElementById('reservationFilter').addEventListener('change',renderReservations);document.getElementById('newReservation').addEventListener('click',function(){openReservationForm()});document.getElementById('closeReservationForm').addEventListener('click',function(){editingReservation=-1;togglePanel('reservationForm',false)});document.getElementById('cancelReservation').addEventListener('click',function(){editingReservation=-1;togglePanel('reservationForm',false)});document.getElementById('saveReservation').addEventListener('click',function(){var name=document.getElementById('reservationName').value.trim();if(!name){showToast('Add a customer name');return}var entry={name:name,console:document.getElementById('reservationConsole').value,time:document.getElementById('reservationTime').value,duration:document.getElementById('reservationDuration').value,status:editingReservation>-1?reservations[editingReservation].status:'Confirmed'};if(editingReservation>-1){reservations[editingReservation]=entry;showToast('Reservation changes saved')}else{reservations.push(entry);showToast('Reservation added to the demo')}editingReservation=-1;togglePanel('reservationForm',false);renderReservations()});renderReservations();

  var transactions=[{customer:'Youssef A.',detail:'Station 01 · Cash',amount:35,status:'Paid',time:'11:42'},{customer:'Omar B.',detail:'Station 02 · Wallet',amount:55,status:'Paid',time:'11:26'},{customer:'Karim S.',detail:'Station 05 · Cash',amount:30,status:'Pending',time:'11:08'},{customer:'Hassan M.',detail:'Station 04 · Cash',amount:20,status:'Paid',time:'10:51'},{customer:'Amine L.',detail:'Snack tab · Cash',amount:40,status:'Pending',time:'10:35'},{customer:'Sara N.',detail:'Wallet top-up',amount:100,status:'Refunded',time:'10:12'}];
  (function(s){if(Array.isArray(s))transactions=s;})(demoStore.get('transactions'));
  function renderTransactions(){demoStore.set('transactions',transactions);var filter=document.getElementById('paymentFilter').value,list=document.getElementById('transactionList'),visible=transactions.map(function(item,index){return{item:item,index:index}}).filter(function(entry){return filter==='all'||entry.item.status===filter}),paid=transactions.filter(function(item){return item.status==='Paid'}).reduce(function(sum,item){return sum+item.amount},1134),pending=transactions.filter(function(item){return item.status==='Pending'}).reduce(function(sum,item){return sum+item.amount},0),refunds=transactions.filter(function(item){return item.status==='Refunded'}).length;document.getElementById('paidTotal').textContent=mad(paid);document.getElementById('pendingTotal').textContent=mad(pending);document.getElementById('transactionCount').textContent=transactions.length+12;document.getElementById('refundCount').textContent=refunds;list.innerHTML=visible.map(function(entry){var item=entry.item;return '<article class="list-row"><div><p><b>'+escapeHtml(item.customer)+'</b></p><small>'+escapeHtml(item.detail)+'</small></div><div><span class="row-label">Time</span><b>'+item.time+'</b></div><div><span class="row-label">Amount</span><b>'+mad(item.amount)+'</b></div><div><span class="row-label">Status</span><span class="status-chip">'+item.status+'</span></div><div class="row-actions">'+(item.status==='Pending'?'<button data-pay-action="paid" data-index="'+entry.index+'">Mark paid</button>':'')+(item.status==='Paid'?'<button class="danger" data-pay-action="refund" data-index="'+entry.index+'">Refund</button>':'')+'</div></article>'}).join('');document.getElementById('paymentEmpty').style.display=visible.length?'none':'block';list.querySelectorAll('[data-pay-action]').forEach(function(btn){btn.addEventListener('click',function(){transactions[Number(btn.dataset.index)].status=btn.dataset.payAction==='paid'?'Paid':'Refunded';renderTransactions();showToast(btn.dataset.payAction==='paid'?'Payment marked paid':'Demo payment refunded')})})}
  document.getElementById('paymentFilter').addEventListener('change',renderTransactions);document.getElementById('exportPayments').addEventListener('click',function(){var csv='Customer,Detail,Amount MAD,Status,Time\n'+transactions.map(function(item){return [item.customer,item.detail,item.amount,item.status,item.time].map(function(value){return '"'+String(value).replace(/"/g,'""')+'"'}).join(',')}).join('\n'),blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='lounge-demo-payments.csv';link.click();URL.revokeObjectURL(url);showToast('Demo payment CSV downloaded')});renderTransactions();

  var customers=[{name:'Youssef Amrani',phone:'06 ** ** 41 72',tier:'Gold',visits:18,points:640,wallet:120},{name:'Omar Bennani',phone:'06 ** ** 93 15',tier:'Silver',visits:13,points:390,wallet:45},{name:'Hassan Mansouri',phone:'07 ** ** 22 08',tier:'Bronze',visits:9,points:180,wallet:0},{name:'Karim Saidi',phone:'06 ** ** 77 31',tier:'Silver',visits:12,points:335,wallet:80},{name:'Salma Rahmani',phone:'06 ** ** 58 04',tier:'Gold',visits:16,points:520,wallet:150},{name:'Mehdi Rami',phone:'07 ** ** 14 66',tier:'Bronze',visits:7,points:130,wallet:20},{name:'Amine Lakhdar',phone:'06 ** ** 09 43',tier:'Guest',visits:3,points:45,wallet:0},{name:'Rania Khalfi',phone:'07 ** ** 35 19',tier:'Bronze',visits:5,points:90,wallet:30}],editingCustomer=-1;
  (function(s){if(Array.isArray(s))customers=s;})(demoStore.get('customers'));
  function openCustomerForm(index){editingCustomer=typeof index==='number'?index:-1;var item=editingCustomer>-1?customers[editingCustomer]:{name:'',phone:'',tier:'Guest',wallet:0};document.getElementById('newCustomerName').value=item.name;document.getElementById('newCustomerPhone').value=item.phone;document.getElementById('newCustomerTier').value=item.tier;document.getElementById('newCustomerWallet').value=item.wallet;document.getElementById('customerFormTitle').textContent=editingCustomer>-1?'Edit customer':'Add customer';document.getElementById('saveCustomer').textContent=editingCustomer>-1?'Save changes':'Add to list';togglePanel('customerForm',true);document.getElementById('customerForm').scrollIntoView({behavior:'smooth',block:'center'})}
  function renderCustomers(){demoStore.set('customers',customers);var query=document.getElementById('customerSearch').value.toLowerCase().trim(),tier=document.getElementById('tierFilter').value,grid=document.getElementById('customerGrid'),visible=customers.map(function(item,index){return{item:item,index:index}}).filter(function(entry){return(!query||entry.item.name.toLowerCase().indexOf(query)>-1||entry.item.phone.indexOf(query)>-1)&&(tier==='all'||entry.item.tier===tier)});grid.innerHTML=visible.map(function(entry){var item=entry.item,initials=item.name.split(' ').map(function(part){return part.charAt(0)}).slice(0,2).join('');return '<article class="customer-card"><div class="customer-head"><div class="customer-id"><span class="customer-avatar">'+escapeHtml(initials)+'</span><div><b>'+escapeHtml(item.name)+'</b><small>'+escapeHtml(item.phone)+'</small></div></div><span class="tier">'+item.tier+'</span></div><div class="customer-metrics"><div><span>VISITS</span><strong>'+item.visits+'</strong></div><div><span>POINTS</span><strong>'+item.points+'</strong></div><div><span>WALLET</span><strong>'+item.wallet+' MAD</strong></div></div><div class="row-actions"><button data-customer-action="edit" data-index="'+entry.index+'">Edit</button><button data-customer-action="wallet" data-index="'+entry.index+'">+20 MAD</button><button data-customer-action="points" data-index="'+entry.index+'">+10 points</button><button data-customer-action="redeem" data-index="'+entry.index+'">Redeem 50</button></div></article>'}).join('');document.getElementById('customerCount').textContent=customers.length;document.getElementById('pointsTotal').textContent=customers.reduce(function(sum,item){return sum+item.points},0).toLocaleString('en-US');document.getElementById('customerResultCount').textContent=visible.length+' shown';document.getElementById('customerEmpty').style.display=visible.length?'none':'block';grid.querySelectorAll('[data-customer-action]').forEach(function(btn){btn.addEventListener('click',function(){var index=Number(btn.dataset.index),item=customers[index],action=btn.dataset.customerAction;if(action==='edit'){openCustomerForm(index);return}if(action==='points'){item.points+=10;showToast('10 loyalty points added')}else if(action==='wallet'){item.wallet+=20;showToast('20 MAD added to the demo wallet')}else if(item.points>=50){item.points-=50;showToast('50 points redeemed')}else{showToast('Not enough points to redeem')}renderCustomers()})})}
  document.getElementById('customerSearch').addEventListener('input',renderCustomers);document.getElementById('tierFilter').addEventListener('change',renderCustomers);document.getElementById('newCustomer').addEventListener('click',function(){openCustomerForm()});document.getElementById('closeCustomerForm').addEventListener('click',function(){editingCustomer=-1;togglePanel('customerForm',false)});document.getElementById('cancelCustomer').addEventListener('click',function(){editingCustomer=-1;togglePanel('customerForm',false)});document.getElementById('saveCustomer').addEventListener('click',function(){var name=document.getElementById('newCustomerName').value.trim();if(!name){showToast('Add a customer name');return}var existing=editingCustomer>-1?customers[editingCustomer]:null,entry={name:name,phone:document.getElementById('newCustomerPhone').value,tier:document.getElementById('newCustomerTier').value,visits:existing?existing.visits:0,points:existing?existing.points:0,wallet:Number(document.getElementById('newCustomerWallet').value)||0};if(editingCustomer>-1){customers[editingCustomer]=entry;showToast('Customer changes saved')}else{customers.unshift(entry);showToast('Customer added to the demo')}editingCustomer=-1;togglePanel('customerForm',false);renderCustomers()});renderCustomers();

  var games=[{title:'EA Sports FC 26',platform:'PS4 + PS5',genre:'Sports',premium:5,available:true},{title:'eFootball',platform:'PS4 + PS5',genre:'Sports',premium:0,available:true},{title:'Call of Duty',platform:'PS5',genre:'Shooter',premium:5,available:true},{title:'GTA V',platform:'PS4 + PS5',genre:'Action',premium:0,available:true},{title:'Tekken 8',platform:'PS5',genre:'Fighting',premium:5,available:true},{title:'Gran Turismo 7',platform:'PS5',genre:'Racing',premium:5,available:true},{title:'Minecraft',platform:'PS4 + PS5',genre:'Party',premium:0,available:false}],editingGame=-1;
  (function(s){if(Array.isArray(s))games=s;})(demoStore.get('games'));
  function gameInitials(title){return title.split(/\s+/).map(function(word){return word.charAt(0)}).slice(0,3).join('').toUpperCase()}
  function syncGameSelectors(){['gameSelect','eventGame'].forEach(function(id){var select=document.getElementById(id),value=select.value,available=games.filter(function(game){return game.available});select.innerHTML=available.map(function(game){return '<option>'+escapeHtml(game.title)+'</option>'}).join('');if(available.some(function(game){return game.title===value}))select.value=value})}
  function openGameForm(index){editingGame=typeof index==='number'?index:-1;var item=editingGame>-1?games[editingGame]:{title:'',platform:'PS4 + PS5',genre:'Sports',premium:0};document.getElementById('newGameTitle').value=item.title;document.getElementById('newGamePlatform').value=item.platform;document.getElementById('newGameGenre').value=item.genre;document.getElementById('newGamePremium').value=String(item.premium);document.getElementById('gameFormTitle').textContent=editingGame>-1?'Edit game':'Add game';document.getElementById('saveGame').textContent=editingGame>-1?'Save changes':'Add to catalog';togglePanel('gameForm',true);document.getElementById('gameForm').scrollIntoView({behavior:'smooth',block:'center'})}
  function renderGames(){demoStore.set('games',games);var query=document.getElementById('gameSearch').value.toLowerCase().trim(),platform=document.getElementById('gamePlatformFilter').value,list=document.getElementById('gameList'),visible=games.map(function(item,index){return{item:item,index:index}}).filter(function(entry){return(!query||entry.item.title.toLowerCase().indexOf(query)>-1||entry.item.genre.toLowerCase().indexOf(query)>-1)&&(platform==='all'||entry.item.platform.indexOf(platform)>-1)});var activeTitles=Array.from(new Set(stationData.filter(activeSession).map(function(item){return item.game})));list.innerHTML=visible.map(function(entry){var item=entry.item;return '<article class="game-item '+(item.available?'':'offline')+'"><div class="game-art">'+escapeHtml(gameInitials(item.title))+'</div><div><b>'+escapeHtml(item.title)+'</b><small>'+escapeHtml(item.genre)+(activeTitles.indexOf(item.title)>-1?' · Active now':'')+'</small></div><div><span class="row-label">Platforms</span><div class="platform-pills">'+item.platform.split(' + ').map(function(value){return '<span class="platform-pill">'+value+'</span>'}).join('')+'</div></div><div><span class="row-label">Premium</span><b>'+(item.premium?'+'+item.premium+' MAD':'Standard')+'</b></div><div class="game-actions"><button data-game-action="edit" data-index="'+entry.index+'">Edit</button><button data-game-action="toggle" data-index="'+entry.index+'">'+(item.available?'Hide':'Show')+'</button><button class="danger" data-game-action="remove" data-index="'+entry.index+'">Remove</button></div></article>'}).join('');document.getElementById('gameCount').textContent=games.length;document.getElementById('availableGameCount').textContent=games.filter(function(game){return game.available}).length;document.getElementById('activeTitleCount').textContent=activeTitles.length;document.getElementById('gameEmpty').style.display=visible.length?'none':'block';list.querySelectorAll('[data-game-action]').forEach(function(btn){btn.addEventListener('click',function(){var index=Number(btn.dataset.index),action=btn.dataset.gameAction;if(action==='edit'){openGameForm(index);return}if(action==='toggle'){games[index].available=!games[index].available;showToast(games[index].title+(games[index].available?' is available':' hidden from session setup'))}else{var removed=games.splice(index,1)[0];showToast(removed.title+' removed from the demo catalog')}syncGameSelectors();renderGames()})})}
  document.getElementById('newGame').addEventListener('click',function(){openGameForm()});document.getElementById('closeGameForm').addEventListener('click',function(){editingGame=-1;togglePanel('gameForm',false)});document.getElementById('cancelGame').addEventListener('click',function(){editingGame=-1;togglePanel('gameForm',false)});document.getElementById('gameSearch').addEventListener('input',renderGames);document.getElementById('gamePlatformFilter').addEventListener('change',renderGames);document.getElementById('saveGame').addEventListener('click',function(){var title=document.getElementById('newGameTitle').value.trim();if(!title){showToast('Add a game title');return}var existing=editingGame>-1?games[editingGame]:null,entry={title:title,platform:document.getElementById('newGamePlatform').value,genre:document.getElementById('newGameGenre').value,premium:Number(document.getElementById('newGamePremium').value),available:existing?existing.available:true};if(editingGame>-1){games[editingGame]=entry;showToast('Game details updated')}else{games.unshift(entry);showToast(title+' added to the lounge catalog')}editingGame=-1;togglePanel('gameForm',false);syncGameSelectors();renderGames()});document.getElementById('scanActiveGames').addEventListener('click',function(){var added=0;stationData.filter(activeSession).forEach(function(station){if(station.game&&games.every(function(game){return game.title.toLowerCase()!==station.game.toLowerCase()})){games.push({title:station.game,platform:station.type.indexOf('5')>-1?'PS5':'PS4',genre:'Action',premium:0,available:true});added++}});syncGameSelectors();renderGames();showToast(added?added+' active title'+(added>1?'s':'')+' imported':'Active titles already match the catalog')});syncGameSelectors();renderGames();

  document.querySelector('.icon-btn').addEventListener('click',function(){showToast('No new notifications')});

  var dailyRevenue=[1195,1242,1427,1441,1431,1248,1196,1138,1081,1189,1167,1167,1040,1077,1121,1158,1334,1338,1324,1141,1101,1062,1033,1175,1188,1225,1127,1187,1243,1286,1456,1453,1427,1234,1185,1139,1108,1245,1254,1280,1167,1205,1232,1243,1381,1350,1302,1098,1047,1012,1000,1159,1193,1243,1150,1203,1242,1261,1408,1384,1349,1162,1131,1118,1123,1300,1340,1389,1283,1313,1322,1308,1421,1367,1307,1102,1063,1044,1050,1225,1266,1311,1199,1223,1226,1209,1326,1287,1249,1075,1070,1087];
  function mad(value){return value.toLocaleString('en-US')+' MAD'}
  function demoDate(index){return new Date(Date.UTC(2026,6,1+index))}
  function labelDate(date){return date.toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'})}
  function renderAnalytics(){var total=dailyRevenue.reduce(function(sum,value){return sum+value},0),average=Math.round(total/dailyRevenue.length),peak=Math.max.apply(null,dailyRevenue),peakIndex=dailyRevenue.indexOf(peak),sessions=dailyRevenue.reduce(function(sum,value){return sum+Math.round(value/31)},0);document.getElementById('demoTotal').textContent=mad(total);document.getElementById('demoAverage').textContent=mad(average);document.getElementById('demoPeak').textContent=mad(peak);document.getElementById('demoPeakDate').textContent=labelDate(demoDate(peakIndex))+' · highest demo day';document.getElementById('demoSessions').textContent=sessions.toLocaleString('en-US');
    var svg=document.getElementById('revenueChart'),left=53,right=17,top=18,bottom=32,width=820,height=280,plotW=width-left-right,plotH=height-top-bottom,min=900,max=1500;function x(i){return left+i/(dailyRevenue.length-1)*plotW}function y(v){return top+(max-v)/(max-min)*plotH}var line=dailyRevenue.map(function(value,index){return (index?'L':'M')+x(index).toFixed(1)+' '+y(value).toFixed(1)}).join(' '),area=line+' L '+x(dailyRevenue.length-1).toFixed(1)+' '+y(min).toFixed(1)+' L '+x(0).toFixed(1)+' '+y(min).toFixed(1)+' Z',markup='';[1000,1250,1500].forEach(function(tick){markup+='<line class="chart-axis" x1="'+left+'" y1="'+y(tick)+'" x2="'+(width-right)+'" y2="'+y(tick)+'"></line><text class="chart-label" x="'+(left-8)+'" y="'+(y(tick)+3)+'" text-anchor="end">'+tick.toLocaleString('en-US')+'</text>'});[{i:0,t:'Jul 1',a:'start'},{i:31,t:'Aug 1',a:'middle'},{i:62,t:'Sep 1',a:'middle'},{i:91,t:'Sep 30',a:'end'}].forEach(function(mark){markup+='<text class="chart-label" x="'+x(mark.i)+'" y="'+(height-7)+'" text-anchor="'+mark.a+'">'+mark.t+'</text>'});markup+='<path class="chart-area" d="'+area+'"></path><path class="chart-line" d="'+line+'"></path><circle class="chart-dot" cx="'+x(peakIndex)+'" cy="'+y(peak)+'" r="4"></circle><text class="chart-label" x="'+x(peakIndex)+'" y="'+(y(peak)-9)+'" text-anchor="middle">'+peak.toLocaleString('en-US')+'</text>';svg.innerHTML=markup;
    var monthNames=['July','August','September'],ranges=[[0,31],[31,62],[62,92]],monthData=ranges.map(function(range,index){var values=dailyRevenue.slice(range[0],range[1]),monthTotal=values.reduce(function(sum,value){return sum+value},0);return{name:monthNames[index],days:values.length,total:monthTotal,avg:Math.round(monthTotal/values.length)}}),maxMonth=Math.max.apply(null,monthData.map(function(item){return item.total}));document.getElementById('monthList').innerHTML=monthData.map(function(item){return '<article class="month-card"><div class="month-card-head"><div><h3>'+item.name+' 2026</h3><p>'+item.days+' operating days · '+mad(item.avg)+'/day</p></div><strong>'+mad(item.total)+'</strong></div><div class="mini-track"><i style="--w:'+Math.round(item.total/maxMonth*100)+'%"></i></div></article>'}).join('');
    var recent=[];for(var i=dailyRevenue.length-1;i>=dailyRevenue.length-8;i--){var value=dailyRevenue[i],dailySessions=Math.round(value/31),occupancy=Math.round(51+(value-1000)/24);recent.push('<div class="ledger-row"><span>'+labelDate(demoDate(i))+', 2026</span><span>'+dailySessions+'</span><span>'+occupancy+'%</span><b>'+mad(value)+'</b></div>')}document.getElementById('ledgerRows').innerHTML=recent.join('')}
  renderAnalytics();

  setInterval(function(){stationData.forEach(function(item,index){if(!activeSession(item)||item.paused||item.remaining<=0)return;item.elapsed+=1;item.remaining-=1;item.time=formatClock(item.elapsed);item.state=Math.max(1,Math.ceil(item.remaining/60))+' min left';if(item.remaining<=600)item.status=Math.max(1,Math.ceil(item.remaining/60))+' min';if(item.remaining===0){item.status='Time up';item.state='Awaiting staff';item.history.unshift('Time expired · Awaiting checkout')}syncOverview(index)});if(document.getElementById('stationsView').classList.contains('active')){var item=stationData[selectedIndex];document.getElementById('consoleTimer').textContent=item.time;document.getElementById('consoleState').textContent=displayState(item)}if(drawer.classList.contains('open'))refreshDrawer()},1000);

  document.getElementById('roleSelect').addEventListener('change',function(){var role=this.value;document.body.classList.toggle('role-limited',role!=='owner');document.body.classList.toggle('role-worker',role==='worker');if(role!=='owner'&&(document.getElementById('analyticsView').classList.contains('active')||document.getElementById('gamesView').classList.contains('active')))showView('overview');document.getElementById('greeting').textContent=role==='owner'?'Good morning, Boss':(role==='supervisor'?'Good morning, Supervisor':'Good morning, Team');document.getElementById('accessTitle').textContent=role==='worker'?'Worker access':'Supervisor access';showToast(role.charAt(0).toUpperCase()+role.slice(1)+' view active')});
})();
